### ISSUE TITLE
Object.values is not supported in IE11

### ISSUE THREAD

**Issue by codymullins** [sciactive/nonblockjs#1]
`values()` is not supported in IE11: https://caniuse.com/#search=values

![image](https://user-images.githubusercontent.com/1738479/37244220-9c98bbc6-2453-11e8-8f85-17dda7bbf8d7.png)

**Comment by codymullins** [comment]
I've created a pull request for the fix: https://github.com/sciactive/nonblockjs/pull/2

**Comment by hperrin** [comment]
Merged.
